name: dart_rope
description: An implementation of the Rope data structure in Dart.
version: 0.1.0
homepage: https://github.com/Peter-Van-Drunen
author: Peter Van Drunen <peter.b.vandrunen@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
